#include "animation/interval-animation.h"
#include "animation/ease-animation.h"
#include "animation/circular-animation.h"
#include "animation/lissajous-animation.h"
#include "animation/point-animation.h"