// Add an include for each primitive
#include "primitives/primitive.h"
#include "primitives/plane-primitive.h"
#include "primitives/sphere-primitive.h"
#include "primitives/union-primitive.h"
#include "primitives/decorator-primitive.h"
#include "primitives/transformer-primitive.h"
#include "primitives/triangle-primitive.h"
#include "primitives/cone-along-y-primitive.h"
#include "primitives/square-primitive.h"
#include "primitives/cone-along-x-primitive.h"
#include "primitives/cylinder-along-x-primitive.h"
#include "primitives/cone-along-y-primitive.h"
#include "primitives/bounding-box-primitive.h"
#include "primitives/mesh-primitve.h"
#include "primitives/cone-along-z-primitive.h"

